### PR TITLE
Window 10 Defender removed 2 unconnected to website files as viruses.

### PR DESCRIPTION
**Pull request by kangarooo**
https://www.microsoft.com/en-us/wdsi/threats/malware-encyclopedia-description?name=Backdoor%3aIRC%2fFserver.gen&threatid=2147594805

### CODE REVIEW

**Comment by bw1** [comment]
submission to MS

**Comment by bw1** [comment]
MS:

> At this time, the submitted files do not meet our criteria for malware or potentially unwanted applications.

**Comment by bw1** [comment]
MS:
> At this time, the submitted files do not meet our criteria for malware or
> potentially unwanted applications. The detection has been removed. Please
> follow the steps below to clear cached detections and obtain the latest malware
> definitions.
> 
> 	 1. Open command prompt as administrator and change directory to 
>       c:\Program Files\Windows Defender
>    2. Run “MpCmdRun.exe -removedefinitions -dynamicsignatures”
>    3. Run "MpCmdRun.exe -SignatureUpdate"
> 
> Alternatively, the latest definition is available for download here: 
> https://docs.microsoft.com/microsoft-365/security/defender-endpoint/manage-updates-baselines-microsoft-defender-antivirus
> 
> Thank you for contacting Microsoft.

@kangarooo close?

**Comment by kangarooo** [comment]
Huh? So why its not showing now as virus? How virus defender now thinks its not?

> submission to MS

What this means? Where to submit to check if not false positive?

**Comment by bw1** [comment]
<https://www.microsoft.com/en-us/wdsi/filesubmission>

**Pull request closed without merging**
