### PR TITLE
upgrade rusnet

### PR DESCRIPTION
**Pull request by bw1**

### CODE REVIEW

**Comment by bw1** [comment]
@kangarooo

**Comment by kangarooo** [comment]
Netherlands and Ukraine are in Europe, Russian language is in Asia.
Previous description was about postsoviet, but theres no postsoviet, all were before soviet occupation.
Netherland was before, so nothing to do with propaganda of their servers.
If that is what thouse servers think, then are not serious but fake servers.
Rusnet means Russian so not Netherlands.
Each sentence is different argument for each mistake
Mistake was putting globalist imperialist war mongering and foreign language pushing propaganda servers, as their original descripton now you are trying to hide to keep it without reason.

**Comment by bw1** [comment]
> That irc server doesnt even have normal working website- more then half pages are broken
yes, it is. but the name of the game is irc 
> THe size mentioned of 343 users
a small group of people
> Russian language is in Asia
a language or a system for communication like irc

**Comment by kangarooo** [comment]
Didnt had any answers about how would servers be connected to netherland and ukraine?
Now i see one is ukraine domain used or was written that it was there.

Description hiding- any language speaking can make language topic channel in any server. So here description is just propaganda.
Theres no proof of Ukraine or Netherlands agreeing on beeing called Russian speaking community.

How to find servers and info you posting?
I see this https://netsplit.de/networks/status.php?net=RusNet shows only irc.lucky.net:6660 but .net doesnt mean description includes where net isnt blocked, its just to circumvent blocking of server.
Where is RU a UA and NL related? From where you found this is beeing used in UA and NL? Just because i speak 5 languages doesnt make countries i travel around to be thouse language speaking countries..

and in https://netsplit.de/servers/?net=RusNet is mentioned only
irc.ventelo.de	irc.run.net	to them connection timed out or failed to get IP in previous link
only irc.lucky.net	is connecting.

Also ip location of server or registation services of domain doesnt mean its related to server services when the description clearly was propaganda.

> > That irc server doesnt even have normal working website- more then half pages are broken
> 
> yes, it is. but the name of the game is irc

The name here is disinformation server intentions

> > THe size mentioned of 343 users
> 
> a small group of people


Then need to put some of 100 irc networks/servers and this one is not in top100 
https://netsplit.de/networks/top100.php

Why is it important to keep with propaganda descriptions or hiding old with new propaganda of RusNet beeing Netherlands and Ukraine?

> > Russian language is in Asia
> 
> a language or a system for communication like irc

its for Russian not Netherlands or Ukraine to what was hidden description
Here is mentioned server is in Ukraine only registered also trace shows that just registrant was there, doesnt make Ukraine new language of Russians beeing on internet no matter if they travel around doesnt change language in other countries
https://netsplit.de/networks/RusNet/

**Comment by bw1** [comment]
```
/connect irc.lucky.net
...
```

```
/links
20:42 -!- irc.lucky.net irc.lucky.net 0 LuckyNet/Kyiv RusNet IRC server
20:42 -!- irc.meganet.ru irc.lucky.net 1 Meganet RusNet Server
20:42 -!- irc.run.net irc.meganet.ru 2 Saint-Petersburg server of RusNet IRC
20:42 -!- *.RusNet irc.run.net 3 Services for RusNet IRC Network
20:42 -!- irc.tomsk.net irc.run.net 3 Tomsk IRC Server, RusNet IRC network
20:42 -!- irc.intertax.ru irc.tomsk.net 4 Intertax RusNet IRC server (Krasnoyarsk, Siberia)
20:42 -!- irc.anarxi.st irc.run.net 3 [176.105.254.200] anarxi.st Italy (BREEZLE LLC), RusNet IRC
20:42 -!- irc.tambov.ru irc.meganet.ru 2 [195.19.116.14] Tambov RusNet Server
20:42 -!- irc.tom.ru irc.tomsk.net 4 [93.170.100.205] Tomsk Academ IRC Server
20:42 -!- * End of LINKS list.
```

### 20:42 -!- irc.lucky.net irc.lucky.net 0 LuckyNet/Kyiv RusNet IRC server
```
/motd irc.lucky.net
20:47 -!- - irc.lucky.net Message of the Day - 
20:47 -!- - 17/11/2017 0:32
20:47 -!- - =======================================================================
20:47 -!- - RusNet IRC Network             irc.lucky.net (Kiev, Ukraine) IRC Server
...
```

```
$ host irc.lucky.net
irc.lucky.net has address 62.149.7.206

$ whois 62.149.7.206
...
address:        Kiev
address:        Ukraine
...
```

### 20:42 -!- irc.anarxi.st irc.run.net 3 [176.105.254.200] anarxi.st Italy (BREEZLE LLC), RusNet IRC
```
/motd irc.anarxi.st
20:50 -!- [irc.anarxi.st] - irc.anarxi.st Message of the Day - 
20:50 -!- [irc.anarxi.st] - 25/6/2014 15:03
20:50 -!- [irc.anarxi.st] - 
20:50 -!- [irc.anarxi.st] - IRC Network                                         irc.anarxi.st
20:50 -!- [irc.anarxi.st] - -----------------------------------------------------------------------
20:50 -!- [irc.anarxi.st] -        Welcome to irc.anarxi.st, located in Netherlands
```

Italy, Netherlands ?


```
$ host irc.anarxi.st
irc.anarxi.st has address 176.105.254.200
irc.anarxi.st has IPv6 address 2a0d:c740:1c:1::6fe:817c

$ whois 176.105.254.200
...
inetnum:        176.105.254.0 - 176.105.254.255
netname:        BREEZLE-2-IT
geoloc:         45.464211 9.191383
...

**Pull request merged**
